"""Add device config fields

Revision ID: bd3ff2ee5e49
Revises: 0ff41f7fc03f
Create Date: 2025-12-06 22:09:25.532019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3ff2ee5e49'
down_revision: Union[str, Sequence[str], None] = '0ff41f7fc03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('clock_frequency', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('memory_bandwidth', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('supported_dtypes', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('architecture_type', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('sparsity_support', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('crossbar_topology', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('firmware_version', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('power_profile', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('thermal_throttling', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('supported_activations', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('supported_layers', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('leakage_types', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_workflow_status_device_id'), 'workflow_status', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_status_device_id'), table_name='workflow_status')
    op.drop_column('devices', 'leakage_types')
    op.drop_column('devices', 'supported_layers')
    op.drop_column('devices', 'supported_activations')
    op.drop_column('devices', 'thermal_throttling')
    op.drop_column('devices', 'power_profile')
    op.drop_column('devices', 'firmware_version')
    op.drop_column('devices', 'crossbar_topology')
    op.drop_column('devices', 'sparsity_support')
    op.drop_column('devices', 'architecture_type')
    op.drop_column('devices', 'supported_dtypes')
    op.drop_column('devices', 'memory_bandwidth')
    op.drop_column('devices', 'clock_frequency')
    # ### end Alembic commands ###
